### ISSUE TITLE
Single Wave.

### ISSUE THREAD

**Issue by mukyasa** [KittenYang/KYWaterWaveView#6]
Hello friend,I have requirement  in which i have to control the number of waves. Can u advice me how it can be done .
Thanks

![textfield](https://cloud.githubusercontent.com/assets/7480780/8776142/81da1a6c-2f0c-11e5-9440-63240eb2990f.gif)

**Comment by KittenYang** [comment]
use UIBezierPath driven by CADisplayLink.
